### ISSUE TITLE
devrel generates nodes that do not launch

### ISSUE THREAD

**Issue by cmeiklejohn** [marianoguerra/rebar3_template_riak_core#14]
@licenser @joedevivo @tsloughter

It looks like `rebar3_cuttlefish` is generating a start script for the environment that contains the runner etc directory twice:

```
_build/default/plugins/rebar3_cuttlefish/priv/bin_script:RUNNER_ETC_DIR="${RUNNER_ETC_DIR:-{{ platform_etc_dir }}}"
_build/default/plugins/rebar3_cuttlefish/priv/bin_script:RUNNER_ETC_DIR="${RUNNER_ETC_DIR:-$RELEASE_ROOT_DIR/etc}"
```

This results in, after running `make devrel`, the configuration file being invalid for starting the node, because it's looking in the wrong place.  
[This could be also because `platform_etc_dir` isn't being defined correctly.]

```
Christophers-MacBook-Pro:unir cmeiklejohn$ make dev1-console
/Users/cmeiklejohn/Documents/unir/_build/dev1/rel/unir/bin/unir console
cp: /Users/cmeiklejohn/Documents/unir/_build/dev1/rel/unir/../unir_config/unir.conf: No such file or directory
make: *** [dev1-console] Error 1
Christophers-MacBook-Pro:unir cmeiklejohn$ grep unir_config /Users/cmeiklejohn/Documents/unir/_build/dev1/rel/unir/bin/unir
RUNNER_ETC_DIR="${RUNNER_ETC_DIR:-../unir_config}"
Christophers-MacBook-Pro:unir cmeiklejohn$ 
```

Any thoughts to where the correct place to fix this is?

**Comment by cmeiklejohn** [comment]
See the following generated initialization script.

```
Christophers-MacBook-Pro:unir cmeiklejohn$ grep ^RUNNER_ETC_DIR /Users/cmeiklejohn/Documents/unir/_build/dev1/rel/unir/bin/unir
RUNNER_ETC_DIR="${RUNNER_ETC_DIR:-../unir_config}"
RUNNER_ETC_DIR="${RUNNER_ETC_DIR:-$RELEASE_ROOT_DIR/etc}"
Christophers-MacBook-Pro:unir cmeiklejohn$ 
```

**Comment by marianoguerra** [comment]
it may be related to this PR:

https://github.com/tsloughter/rebar3_cuttlefish/pull/12

**Comment by cmeiklejohn** [comment]
That change doesn't look right; these configuration files are not being generated correctly.  Thoughts @tsloughter?

**Comment by cmeiklejohn** [comment]
Any thoughts on this? @tsloughter

**Comment by tsloughter** [comment]
Sorry, no. Haven't had time to look at this deeper than what is in the issue. I'll try to get time to generate a project from the templates and run it today.

**Comment by marianoguerra** [comment]
the template works again
