### ISSUE TITLE
gen_nb_server.erl failed on OTP-20

### ISSUE THREAD

**Issue by 2trc** [marianoguerra/rebar3_template_riak_core#17]
Hi, 
being an erlang newbie trying to start with riak I'm a bit out of breadth with the tutorial https://marianoguerra.github.io/little-riak-core-book/starting.html

After creating the project, running `rebar3 release` gives me the following error:
```
===> Compiling _build/default/lib/riak_core/src/gen_nb_server.erl failed
_build/default/lib/riak_core/src/gen_nb_server.erl:none: redefining macro 'namespaced_types'
```
I'm assuming it's a version incompatibility issue but since this seems to be a popular tutorial I was surprised not to see a fix online.

Could you please advise how to solve this issue?

**Comment by marianoguerra** [comment]
hi! 

what version of erlang/rebar3 are you using?

can you try this tutorial? it's more up to date: http://marianoguerra.org/tmp/riak-core-tutorial/

eventually I will point to it from the little riak core book.

anyway, I just tried the rebar3 template on erlang 21 and made a small fix, check if it works for you https://github.com/marianoguerra/rebar3_template_riak_core/commit/5d4f1f2e26050dbbcf83bd7c916ae640eb74ceeb

**Comment by marianoguerra** [comment]
Note: if you already downloaded the template pull the latest changes or remove it and download it again

**Comment by 2trc** [comment]
@marianoguerra a `git pull` worked. Thanks a lot. I wouldn't be able to fix this myself
