### ISSUE TITLE
When I run 'rebar3 run', alway tell me 'vm.args needs to have a -name parameter.'

### ISSUE THREAD

**Issue by wudixiaotie** [marianoguerra/rebar3_template_riak_core#9]
└$ rebar3 run
===> Verifying dependencies...
===> Compiling tanodb
===> Running cuttlefish schema generator
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /Users/tiexiao/code/tanodb/_build/default/lib
          /Users/tiexiao/code/tanodb/apps
          /usr/local/Cellar/erlang/18.3/lib/erlang/lib
          /Users/tiexiao/code/tanodb/_build/default/rel
===> Resolved tanodb-0.1.0
===> Dev mode enabled, release will be symlinked
===> release successfully created!
vm.args needs to have a -name parameter.
  -sname is not supported.
  couldn't find 'nodename' in ../tanodb_config/tanodb.conf
  $PWD is /Users/tiexiao/code/tanodb

**Comment by wudixiaotie** [comment]
You should update your README file, change

``` console
rebar3 run
```

TO

``` console
make release
make console
```

**Comment by liuzhen** [comment]
PR would be appreciated.

**Comment by wudixiaotie** [comment]
You are totally right.
